services:
  server:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 9090:9090
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_PORT: ${MYSQL_PORT}
    networks:
      - backend
    depends_on:
      - database

  database:
    image: mysql:8
    restart: unless-stopped
    hostname: ${MYSQL_HOST}
    environment:
      MYSQL_DATABASE: internship # hardcoded here since it's hardcoded in the server code
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:


volumes:
  mysql-data:
